version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

#formats:
#  - htmlzip
#  - pdf
#  - epub

python:
  install:
    - requirements: requirements-doc.txt
    - method: pip
      path: .
  system_packages: false

submodules:
  include: false
